server:
  port: 0
spring:
  profiles:
    active: dev
  application:
    name: tracker-service
eureka:
  client:
    fetchRegistry: false
    registerWithEureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method